### ISSUE TITLE
error when training

### ISSUE THREAD

**Issue by tuyenbk** [dtake1336/ERNN-for-speech-enhancement#2]
I got an error below when trained a model on VoiceBank data. Can you please let me know how to fix it? 
![image](https://user-images.githubusercontent.com/15787566/84145518-05be6900-aa28-11ea-9416-feac7f233667.png)

**Comment by dtake1336** [comment]
Thank you for your comment.
I am trying to reproduce your error but I haven't done it yet in my enviroment.
Could you tell me following when this error occurs?
- the shape of **xtmp**
- the value of **batchTimeFrame** and **shiftLen**

I think you use test dataset as train dataset for trial. 
But, the sampling rate of test dataset may be not 16 kHz but 48 kHz.
Did you downsample test dataset as 16 kHz?

If I can reproduce this error, add solution in this issue.

**Comment by henryxrl** [comment]
I have very similar issue:
![image](https://user-images.githubusercontent.com/7662954/87897800-6d4dd800-ca1a-11ea-837c-58c106645688.png)

My config:
1. I too used the test set from DEMAND for training as a first trial step.
2. All the parameters are unchanged from the default value you provided. batchTimeFrame=68 and shiftLen=256.
3. Your code does not downsample audios. So instead of _wavfile.read_, I used _librosa.load_ which allows me to downsample audio when loading them in. _librosa.load_ also returns dtype == np.float32 directly.

Any help would be appreciated! Thanks!

**Comment by dtake1336** [comment]
Thank you for your report.
I cannot reproduce this error yet.
I think if I comment out following (lines 181, 182, 186, 187 of 01_train.py in this repo), this error may be resolved.
`stmp =  xp.reshape(stmp, (1, batchTimeFrame*shiftLen) )`
`xtmp =  xp.reshape(xtmp, (1, batchTimeFrame*shiftLen) )`
`s = xp.concatenate( (s,stmp), axis=0) `
`x = xp.concatenate( (x,xtmp), axis=0)`
Because **stmp** & **xtmp** are not used after these lines.

**Comment by henryxrl** [comment]
Do you mean by lines 181, 182, 186, 187?

**Comment by dtake1336** [comment]
Yes. I also fixed the above comment

**Comment by henryxrl** [comment]
Hmm after commenting those lines out, I still get similar errors at line 184
`Xtmp =  xp.reshape(Xtmp, (1, chNum, batchTimeFrame) )`
"ValueError: cannot reshape array of size 3084 into shape 17476"

**Comment by dtake1336** [comment]
Could you tell me the shape of **Xtmp** before executing line 184?
In my environment, the shape of **Xtmp** is (257, 68).

**Comment by henryxrl** [comment]
![image](https://user-images.githubusercontent.com/7662954/87906127-00ddd380-ca30-11ea-8545-c02b50f71b10.png)

Notice on the last line, the shape of Xtmp is no longer (257, 68).

**Comment by dtake1336** [comment]
Thank you for reporting!
I have roughly figured out the cause of the error.
I will upload the modified version to the repository as soon as possible.

**Comment by henryxrl** [comment]
Thank you so much for your help! Looking forward to your updated version.

**Comment by henryxrl** [comment]
Oh, and I ran the code three times, but Xtemp.shape gets different shapes each time.

First time:
![image](https://user-images.githubusercontent.com/7662954/87907693-13a5d780-ca33-11ea-8ada-8e8249f26567.png)

Second time:
![image](https://user-images.githubusercontent.com/7662954/87907726-1dc7d600-ca33-11ea-93a7-259fcdf12e67.png)

Third time:
![image](https://user-images.githubusercontent.com/7662954/87907747-27513e00-ca33-11ea-90eb-eeffaccefc89.png)

Is this what it supposed to be?

**Comment by dtake1336** [comment]
No. I created it so that the shape of xtmp is fixed at (chNum, batchTimeFrame).

All data in the train dataset are longer than the **batchTimeFrame*shiftLen** so these errors probably will not occur if train dataset is used.
There is something shorter in the test dataset so this error occured.

I just fixed it, so you should be able to use it without this error.

**Comment by henryxrl** [comment]
I can confirm this problem is fixed. But there's another problem appearing. I'll open another ticket.
